config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'pages/home'

  get 'pages/interview'

  get 'pages/about'

  get 'page/home'

  get 'page/about'

  get 'page/interview'

  devise_for :users
  resources :jobs, only: [:index, :new, :show, :edit, :update, :create, :destroy]
     root "jobs#index"

     get '/jobs/new' => 'jobs/new'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
        end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:category].blank?
    @jobs = Job.all.order("created_at DESC")
  else
          @category_id = Category.find_by(name: params[:category]).id
          @jobs = Job.where(:category_id => @category_id)
      end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
      @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /jobs/1/edit
  def edit
     @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.category_id = params[:category_id]
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
     @job.category_id = params[:category_id]
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company, :salary, :description, :category_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def interview
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= tinymce %>
<div class="container">

<%= simple_form_for(@job, html: { class: 'form-horizontal' }) do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
<div class="well">

  <%= f.input :title, label: "Job Title" %>
  <%= f.input :company, label: "Your Company Name" %>
  <%= f.input :salary, label: "Job Salary" %>
  <%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 120 %>
    <br/>
  <%= f.button :submit, :class => "btn btn-primary btn-lg" %>
        <% end %>

</div>
</div>

app/views/jobs/edit.html.erb
<%= tinymce_assets %>
<%= tinymce %>


<h1>Edit Job</h1>

<%= simple_form_for @job, :html => { :multipart => true } do |f| %>
<%= f.select :category_id, @categories %>
<!--<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>-->
<%= f.input :title, label: "Job Title" %>
<%= f.input :company, label: "Comapny Name:" %>
<%= f.input :salary, label: "Job Salary:" %>
<%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 120 %>

<%= f.button :submit %>
<% end %>
<%= link_to 'Show', @job, :class => 'btn btn-default' %> |
<%= link_to 'Back', jobs_path, :class => 'btn btn-default' %>

app/views/jobs/index.html.erb
<div class="container">
  <div class="well">
<h1 class="job-list">Current Job Listing</h1>
<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
<br/><br/>


<h1 class="current-category"><%= params[:category] %></h1>
    <% @jobs.each do |job| %>

        <h2><%= link_to job.title, job %></h2>
        <h2><%= job.company %></h2>
        <!-- <<%= truncate(job.description.html_safe, :length => 135) %> -->
        <p class="time"><strong>Date Created:</strong> <%= job.created_at.strftime("%B %d, %Y") %></p>
        <%= link_to "Read More", job %>
<hr>
    <% end %>
</div>
</div>

app/views/jobs/new.html.erb
<%= tinymce_assets %>
 <%= tinymce %>
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<div class="container">
  <div class="well">
<h2>Job Title:<%= @job.title %></h2>
<h2> Company Name: <%= @job.company %></h2>
<h3>Salary: <%= @job.salary %></h3>
<h3> Job Details: </h3> <%= @job.description.html_safe %>

<br/>

  <% if current_user.try(:admin?) %>
<%= link_to "Edit", edit_job_path(@job), :class => 'btn btn-danger' %>
<%= link_to "Delete", job_path(@job), :class => 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?"} %>


<% else %>

<p><%= link_to "Apply for this Job Now", '#', :class => 'btn btn-danger' %></p>
<% end %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
       <%= link_to "Job Express", root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path, :class => 'active' %></li>


            <% if current_user.try(:admin?) %>
            <li><%= link_to 'Create New Job', new_job_path %></li>
            <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Registration <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'SignUp', new_user_registration_path  %></li>
              <li role="separator" class="divider"></li>

                <% if current_user %>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                  <li role="separator" class="divider"></li>
                  <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
                  <li role="separator" class="divider"></li>
                   <li><%= link_to 'Edit Profile',  edit_user_registration_path %></li>
                     <li role="separator" class="divider"></li>
                   <li><%= link_to 'Upload CV', '#' %></li>
                  <% else %>
                    <li role="separator" class="divider"></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
              <li role="separator" class="divider"></li>

            <% end %>

            </ul>
          </li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li>Welcome: <%= if user_signed_in? then current_user.name end %></li>
                <li><%= link_to 'Inteview Tips', pages_interview_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Job Category <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">PartTime Jobs</a></li>
                <li role="separator" class="divider"></li>
              <li><a href="#">FullTime Jobs</a></li>
                <li role="separator" class="divider"></li>
              <li><a href="#">Consultancy</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Freelancing</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
  <% end %>





<%= yield %>

</body>
</html>